/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author inito
 */
public class AktualneZlecenia extends javax.swing.JFrame {

    private void close() {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private ModyfikujZlecenia zlecenia = new ModyfikujZlecenia();
     private NowaModyfikacjaZlecenia modyfimacja=new NowaModyfikacjaZlecenia();
    public void AktZlecenia(){
        
                
          DefaultTableModel model=(DefaultTableModel) jTable1.getModel();  
       
    
Connection conn=null;
conn = MysqlConnect.ConnectDB();
PreparedStatement ps=null;
ResultSet rset;

 

//zapytanie do wyjecia danych odnośnie czynnosci serwisowej + sumaryczny koszt czesci
 

String Sql3="select   `id_zlecenie`, wlasciciel.imie, wlasciciel.nazwisko, `data_przyjecia`, `wartosc`, auto.marka, auto.model, auto.id_auto \n" +
"from wlasciciel LEFT JOIN auto\n" +
"on wlasciciel.id_wlasciciel=auto.WLASCICIEL_id_wlasciciel\n" +
"LEFT JOIN zlecenie\n" +
"on auto.id_auto=zlecenie.AUTO_id_auto\n" +
"where zlecenie.data_zakonczenia IS NULL AND zlecenie.id_zlecenie IS NOT NULL\n" +
"group by zlecenie.id_zlecenie";



String Sql4="SELECT zlecenie.id_zlecenie, wlasciciel.imie, wlasciciel.nazwisko,zlecenie.data_przyjecia, definicjacs.kosztrobocizny, auto.marka, auto.model, auto.id_auto\n" +
"FROM zlecenie \n" +
"join czynnoscserwisowa on zlecenie.id_zlecenie=czynnoscserwisowa.ZLECENIE_id_zlecenie\n" +
"join definicjacs on definicjacs.ID_DEFINICJACS=czynnoscserwisowa.DEFINICJACS_ID_DEFINICJACS\n" +
"join wlasciciel on zlecenie.WLASCICIEL_id_wlasciciel=wlasciciel.id_wlasciciel\n" +
"JOIN auto on auto.id_auto=zlecenie.AUTO_id_auto\n" +
"\n" +
"WHERE czynnoscserwisowa.data_zakonczenia is null\n" +
"\n" +
"group by zlecenie.id_zlecenie";

for(int i=model.getRowCount()-1;i>=0;i--)
{
    model.removeRow(i);
}
    try{
ps = conn.prepareStatement(Sql4);
rset=ps.executeQuery();



                while(rset.next()==true){
                  
                     //zapytanie do wyjecia sumy cześci zamiennych potrzebnych do wykonania danej czynnosci serwisowej
  
                                model.addRow(new Object[]{
                                    rset.getString(1),
                                    rset.getString(2),
                                    rset.getString(3),
                                    rset.getString(4),
                                    rset.getString(5),
                                    rset.getString(6),
                                    rset.getString(7),
                                    rset.getString(8)
                                });
                
                }
}
catch(Exception e){
 JOptionPane.showMessageDialog(null, e);
}
    
    }
    
    public AktualneZlecenia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText("Modyfikuj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Imię", "Nazwisko", "Data przyjęcia", "Koszt", "Marka Auta", "Model Auta", "Id_Auta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
       if(jTable1.getSelectedRow()!=-1 ){

//Zlecenia zlecenia=new Zlecenia();
        //zlecenia.setVisible(true);
        modyfimacja.setVisible(true);
        
        //pobranie id modelu z kolumny
        
        int idModelu=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        int idZlecenie=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        
        System.err.println("Id modelu ze zlecen :"+idModelu);
        System.err.println("Id  zlecenia :"+idZlecenie);
        
        zlecenia.setModeid(idModelu);
        zlecenia.setZlecenieid(idZlecenie);
        zlecenia.AktualneCS();
        zlecenia.setDostepneCS();
       
        
         modyfimacja.setZlecenieid(idZlecenie);
         modyfimacja.inicjowanie();
         System.err.println("Modyfikacja ->zlecenie :"+modyfimacja.zlecenieid);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AktualneZlecenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AktualneZlecenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AktualneZlecenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AktualneZlecenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AktualneZlecenia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
