/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mariusz Jaczewski
 */
public class NowaModyfikacjaZlecenia extends javax.swing.JFrame {
int modelid;
        int zlecenieid;
    
        
        private void close() {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public void setModeid(int modelid){
        this.modelid = modelid;
    }
    
    
    public int getModelid(){
        return this.modelid;
    }
    
    public void setZlecenieid(int zlecenieid){
        this.zlecenieid=zlecenieid;
    }
    public int getZlecenieid(){
        return this.zlecenieid;
    }
  
 public void inicjowanie(){       
            System.out.println("zlecenieId w inicjacji  "+zlecenieid);    
          DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
         
  model.setRowCount(0);
       
    
Connection conn=null;
conn = MysqlConnect.ConnectDB();
PreparedStatement ps=null;
ResultSet rset;


//model.setRowCount(0);

//zapytanie do wyjecia danych odnośnie czynnosci serwisowej + sumaryczny koszt czesci
 

String Sql3="  SELECT czynnoscserwisowa.id_czynnoscserwisowa , definicjacs.nazwa, czynnoscserwisowa.data_rozpoczecia, czynnoscserwisowa.data_zakonczenia, czynnoscserwisowa.MECHANIK_id_mechanik, czynnoscserwisowa.STANOWISKO_id_stanowisko\n" +
"  from czynnoscserwisowa \n" +
"  join zlecenie ON zlecenie.id_zlecenie=czynnoscserwisowa.ZLECENIE_id_zlecenie \n" +
"  join definicjacs ON definicjacs.ID_DEFINICJACS=czynnoscserwisowa.DEFINICJACS_ID_DEFINICJACS\n" +
"  where zlecenie.id_zlecenie=  "+zlecenieid;


    try{
ps = conn.prepareStatement(Sql3);
rset=ps.executeQuery();



                while(rset.next()){
                  
                     //zapytanie do wyjecia sumy cześci zamiennych potrzebnych do wykonania danej czynnosci serwisowej
  
                                model.addRow(new Object[]{
                                    rset.getString(1),
                                    rset.getString(2),
                                    rset.getString(3),
                                    rset.getString(4),
                                    rset.getString(5),
                                    rset.getString(6)
                                });
                
                }
}
catch(Exception e){
 JOptionPane.showMessageDialog(null, e);
}
 }
    /**
     * Creates new form NowaModyfikacjaZlecenia
     */
    public NowaModyfikacjaZlecenia() {
         
        initComponents();
         //this.inicjowanie();
    this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Lista czynności serwisowych wchodzacyvh w skład zlecenia:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nazwa", "Data rozpoczęcia", "Data zakończenia", "Id Mechanik", "Id Stanowisko"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Zakończ czynność");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Usuń czynność");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked


    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if(jTable2.getSelectedRow()!=-1){
            
            int czynnoscDoUsuniecia=0; 
            
            czynnoscDoUsuniecia=Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
            
Connection conn=null;
conn = MysqlConnect.ConnectDB();
 


//model.setRowCount(0);

//zapytanie do wyjecia danych odnośnie czynnosci serwisowej + sumaryczny koszt czesci
 

String Sql3="DELETE FROM `czynnoscserwisowa` WHERE czynnoscserwisowa.id_czynnoscserwisowa="+czynnoscDoUsuniecia  ;


    try{
 
Statement smt = conn.createStatement();
smt.executeUpdate(Sql3);
JOptionPane.showMessageDialog(null, "Usunięto czynność serwisową.");
smt.close();

               
}
catch(Exception e){
 JOptionPane.showMessageDialog(null, e);
}
            
   this.inicjowanie();
            
            
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
              if(jTable2.getSelectedRow()!=-1){
            
            int czynnoscDoZmkniecia=0; 
            
            czynnoscDoZmkniecia =Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
            
Connection conn=null;
conn = MysqlConnect.ConnectDB();
 


//model.setRowCount(0);

//zapytanie do wyjecia danych odnośnie czynnosci serwisowej + sumaryczny koszt czesci
 

String Sql3="UPDATE `czynnoscserwisowa` SET  `data_zakonczenia`=NOW()\n" +
"WHERE czynnoscserwisowa.id_czynnoscserwisowa="+czynnoscDoZmkniecia  ;


    try{
 
Statement smt = conn.createStatement();
smt.executeUpdate(Sql3);
JOptionPane.showMessageDialog(null, "Zamknięto czynność serwisową.");
smt.close();

               
}
catch(Exception e){
 JOptionPane.showMessageDialog(null, e);
}
        this.inicjowanie();
    
    boolean czyZakonczona=true;
    
    
    for(int i =0; i<jTable2.getRowCount();i++){
        System.out.println("Zakoncznie: "+jTable2.getValueAt(i, 3));
        if(jTable2.getValueAt(i, 3)==null){
           czyZakonczona=false; 
        }
         
    }
    
    if(czyZakonczona==true){
        JOptionPane.showMessageDialog(null, "Zlecenie zostało zakończone");
        
    }
    
    
    
    
    
    
    
    
    
    this.inicjowanie();
              }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NowaModyfikacjaZlecenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NowaModyfikacjaZlecenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NowaModyfikacjaZlecenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NowaModyfikacjaZlecenia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NowaModyfikacjaZlecenia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
